import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '@/theme/theme';
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "Gamesngo",
  description: "Generated by create next app",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  themeColor: "#4848DB",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Prevent Brave wallet injection errors - must run first
              (function() {
                try {
                  // Handle both ethereum and etherum (Brave typo)
                  Object.defineProperty(window, 'ethereum', {
                    configurable: true,
                    enumerable: true,
                    get: function() { return undefined; },
                    set: function() {}
                  });
                  Object.defineProperty(window, 'etherum', {
                    configurable: true,
                    enumerable: true,
                    get: function() { return undefined; },
                    set: function() {}
                  });
                } catch(e) {
                  console.log('Wallet prevention script:', e);
                }
              })();
            `,
          }}
        />
        <meta name="theme-color" content="#4848DB" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      </head>
      <body className={`${inter.variable} gradient-body`}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <div className="content-container">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
